const sampleProperties = [
  {
    name: "Modern Downtown Apartment",
    address: "123 Main Street, Downtown",
    price: 350000,
    description:
      "A beautiful modern apartment in the heart of downtown with city views and premium amenities.",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1200,
    propertyType: "Apartment",
    yearBuilt: 2020,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_1",
    features: ["parking", "balcony", "gym", "pool", "concierge"],
    coordinates: { latitude: 40.7128, longitude: -74.006 },
    image: "/images/1.jpg",
  },
  {
    name: "Luxury Suburban Villa",
    address: "456 Oak Avenue, Suburbs",
    price: 850000,
    description:
      "Spacious luxury villa with garden, pool, and three-car garage in exclusive neighborhood.",
    bedrooms: 4,
    bathrooms: 3,
    squareFootage: 3200,
    propertyType: "House",
    yearBuilt: 2018,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_2",
    features: ["garden", "pool", "garage", "fireplace", "wine_cellar"],
    coordinates: { latitude: 40.758, longitude: -73.9855 },
    image: "/images/2.jpg",
  },
  {
    name: "Cozy Studio Loft",
    address: "789 Pine Street, Arts District",
    price: 250000,
    description:
      "Cozy studio loft in the trendy arts district with exposed brick walls and high ceilings.",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 800,
    propertyType: "Loft",
    yearBuilt: 2015,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_3",
    features: ["exposed_brick", "high_ceilings", "artist_space", "hardwood_floors"],
    coordinates: { latitude: 40.7282, longitude: -73.7949 },
    image: "/images/3.jpg",
  },
  {
    name: "Beachfront Condo",
    address: "321 Ocean Drive, Beach City",
    price: 750000,
    description:
      "Stunning beachfront condominium with panoramic ocean views and private beach access.",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1800,
    propertyType: "Condo",
    yearBuilt: 2019,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_4",
    features: ["ocean_view", "balcony", "beach_access", "concierge", "spa"],
    coordinates: { latitude: 25.7617, longitude: -80.1918 },
    image: "/images/4.jpg",
  },
  {
    name: "Historic Townhouse",
    address: "654 Heritage Avenue, Old Town",
    price: 585000,
    description:
      "Charming historic townhouse with original features and modern renovations in prestigious neighborhood.",
    bedrooms: 3,
    bathrooms: 3,
    squareFootage: 2200,
    propertyType: "Townhouse",
    yearBuilt: 1925,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_5",
    features: ["historic", "hardwood_floors", "fireplace", "garden", "original_details"],
    coordinates: { latitude: 39.9526, longitude: -75.1652 },
    image: "/images/5.jpg",
  },
  {
    name: "Penthouse Suite",
    address: "999 Sky Tower, Uptown",
    price: 1200000,
    description:
      "Exclusive penthouse suite with 360-degree city views and private elevator access.",
    bedrooms: 4,
    bathrooms: 4,
    squareFootage: 4000,
    propertyType: "Penthouse",
    yearBuilt: 2021,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_6",
    features: ["city_view", "private_elevator", "rooftop_terrace", "smart_home", "wine_room"],
    coordinates: { latitude: 40.7831, longitude: -73.9712 },
    image: "/images/6.jpg",
  },
  {
    name: "Riverside Studio",
    address: "101 River Walk, Waterfront District",
    price: 185000,
    description:
      "Compact studio with stunning river views and modern amenities. Perfect for young professionals.",
    bedrooms: 1,
    bathrooms: 1,
    squareFootage: 600,
    propertyType: "Studio",
    yearBuilt: 2017,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_7",
    features: ["river_view", "fitness_center", "rooftop_deck", "pet_friendly"],
    coordinates: { latitude: 40.742, longitude: -74.003 },
    image: "/images/7.jpg",
  },
  {
    name: "Family Suburban Home",
    address: "789 Maple Lane, Greenwood Heights",
    price: 425000,
    description: "Charming family home with large backyard and quiet neighborhood setting.",
    bedrooms: 3,
    bathrooms: 2,
    squareFootage: 1800,
    propertyType: "House",
    yearBuilt: 2010,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_8",
    features: ["backyard", "garage", "family_room", "updated_kitchen"],
    coordinates: { latitude: 40.6892, longitude: -73.9442 },
    image: "/images/8.jpg",
  },
  {
    name: "Urban Loft Conversion",
    address: "555 Industrial Way, Arts Quarter",
    price: 395000,
    description: "Converted warehouse loft with exposed beams, brick walls, and industrial charm.",
    bedrooms: 2,
    bathrooms: 1,
    squareFootage: 1400,
    propertyType: "Loft",
    yearBuilt: 1920,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_9",
    features: [
      "exposed_beams",
      "brick_walls",
      "high_ceilings",
      "industrial_design",
      "artist_space",
    ],
    coordinates: { latitude: 40.7245, longitude: -73.9967 },
    image: "/images/9.jpeg",
  },
  {
    name: "Luxury Waterfront Condo",
    address: "777 Harbor View, Marina District",
    price: 895000,
    description: "Spectacular waterfront condominium with marina views and luxury amenities.",
    bedrooms: 3,
    bathrooms: 3,
    squareFootage: 2100,
    propertyType: "Condo",
    yearBuilt: 2021,
    isActive: true,
    createdDate: new Date(),
    updatedDate: new Date(),
    ownerId: "owner_10",
    features: ["marina_view", "balcony", "concierge", "spa", "wine_storage", "valet_parking"],
    coordinates: { latitude: 40.7505, longitude: -74.0134 },
    image: "/images/10.jpg",
  },
]

const sampleOwners = [
  {
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "555-0101",
    photoUrl: "https://example.com/photos/john-smith.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "555-0102",
    photoUrl: "https://example.com/photos/sarah-johnson.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Michael Brown",
    email: "michael.brown@email.com",
    phone: "555-0103",
    photoUrl: "https://example.com/photos/michael-brown.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Emily Davis",
    email: "emily.davis@email.com",
    phone: "555-0104",
    photoUrl: "https://example.com/photos/emily-davis.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "David Wilson",
    email: "david.wilson@email.com",
    phone: "555-0105",
    photoUrl: "https://example.com/photos/david-wilson.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Lisa Martinez",
    email: "lisa.martinez@email.com",
    phone: "555-0106",
    photoUrl: "https://example.com/photos/lisa-martinez.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Robert Taylor",
    email: "robert.taylor@email.com",
    phone: "555-0107",
    photoUrl: "https://example.com/photos/robert-taylor.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Jennifer Anderson",
    email: "jennifer.anderson@email.com",
    phone: "555-0108",
    photoUrl: "https://example.com/photos/jennifer-anderson.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Christopher Thomas",
    email: "christopher.thomas@email.com",
    phone: "555-0109",
    photoUrl: "https://example.com/photos/christopher-thomas.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Amanda Garcia",
    email: "amanda.garcia@email.com",
    phone: "555-0110",
    photoUrl: "https://example.com/photos/amanda-garcia.jpg",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
]

const sampleCategories = [
  {
    name: "Residential",
    description: "Houses, apartments, and other residential properties",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Commercial",
    description: "Office buildings, retail spaces, and commercial properties",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Industrial",
    description: "Warehouses, factories, and industrial facilities",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Land",
    description: "Vacant land, lots, and development opportunities",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    name: "Luxury",
    description: "High-end luxury properties and estates",
    createdDate: new Date(),
    updatedDate: new Date(),
  },
]

module.exports = { sampleProperties, sampleOwners, sampleCategories }
